### ISSUE TITLE
Невозможно задать дополнительные отступы для графика

### ISSUE THREAD

**Issue by BioSin** [dima117/Chart.AltLineChart#1]
Когда по оси задано кратное 10 значение, последняя точка идет без отступов.
http://joxi.ru/xAeJ55psBMGzry
Перечитал всю документацию, не нашел такой настройки.
Когда задано не кратное значение, то отступ добавляется автоматом.

**Comment by dima117** [comment]
Спасибо! Постараюсь исправить сегодня-завтра.

**Comment by dima117** [comment]
Исправлено. Отступ добавляется автоматом, дополнительные настройки указывать не нужно.
