### ISSUE TITLE
Support for scaleOverride, scaleSteps, scaleStepWidth, scaleStartValue from core

### ISSUE THREAD

**Issue by jchesterisidoro** [dima117/Chart.AltLineChart#10]
I tried using these options but nothing changed. So I thought maybe it's still not supported.

**Comment by dima117** [comment]
Yes, it is not supported yet, because it requires the complex logic in case when values are located outside the specified area. Maybe it will be added in near future.

-----Исходное сообщение-----
От: "John Chester Isidoro" notifications@github.com
Отправлено: ‎05.‎06.‎2015 12:03
Кому: "dima117/Chart.Scatter" Chart.Scatter@noreply.github.com
Тема: [Chart.Scatter] Support for scaleOverride, scaleSteps,scaleStepWidth, scaleStartValue from core (#10)

I tried using these options but nothing changed. So I thought maybe it's still not supported.

**Comment by jchesterisidoro** [comment]
But it's already in the core right? So it's already been solved I assume.

**Comment by dima117** [comment]
Yes, this functionality is in core but it has the same error and so it isn't used yet.

-----Исходное сообщение-----
От: "John Chester Isidoro" notifications@github.com
Отправлено: ‎05.‎06.‎2015 19:00
Кому: "dima117/Chart.Scatter" Chart.Scatter@noreply.github.com
Копия: "dima117" dima117a@gmail.com
Тема: Re: [Chart.Scatter] Support for scaleOverride, scaleSteps,scaleStepWidth, scaleStartValue from core (#10)

But it's already in the core right? So it's already been solved I assume.

**Comment by jchesterisidoro** [comment]
That's too bad then. The problem I'm having is that the y-range is too zoomed-in when the y-data have very small differences for example, [27.00, 27.05, 27.056,..., 28]. Do you happen to know any workaround for this? Even using the core's scaleOverride is fine by me. I'm positive that my data won't exceed the specified area.

**Comment by dima117** [comment]
Ok, I will use scale calculation from chartjs core for Y axis. I going to change scatter chart code today.

-----Исходное сообщение-----
От: "John Chester Isidoro" notifications@github.com
Отправлено: ‎06.‎06.‎2015 2:47
Кому: "dima117/Chart.Scatter" Chart.Scatter@noreply.github.com
Копия: "dima117" dima117a@gmail.com
Тема: Re: [Chart.Scatter] Support for scaleOverride, scaleSteps,scaleStepWidth, scaleStartValue from core (#10)

That's too bad then. The problem I'm having is that the y-range is too zoomed-in when the y-data have very small differences for example, [27.00, 27.05, 27.056,..., 28]. Do you happen to know any workaround for this? Even using the core's scaleOverride is fine by me. I'm positive that my data won't exceed the specified area.

**Comment by jchesterisidoro** [comment]
Thank you so much!

**Comment by dima117** [comment]
Done. Scale range option are supported:
- scaleOverride,
- scaleSteps,
- scaleStepWidth,
- scaleStartValue.

Please update your Chart.Scatter.js

**Comment by jchesterisidoro** [comment]
It's working. Thanks!
