### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by ilkkao** [dima117/Chart.AltLineChart#12]
It'd be great to be able to install this library as a npm module in addition to bower support.

**Comment by dima117** [comment]
I will add npm support during next day.

**Comment by dima117** [comment]
I'm sorry, I still didn't create the npm package. It is unknown area for me and it wasn't possible to study it. I will add npm package as soon as possible.

**Comment by dima117** [comment]
Just published this to npm now.

Run:
`npm i chart.js-scatter`

**Comment by ilkkao** [comment]
Really nice. Now I don't need to use bower just to get this one library. Thanks!
