### ISSUE TITLE
Line drawing issue

### ISSUE THREAD

**Issue by Teddy-Schmitz** [dima117/Chart.AltLineChart#13]
Hi,

I am using socket.io to push new points to the chart.  When I call addpoint then update,  the line is redrawn from the first point to the new point instead of from the last point to the new point.

![image](https://cloud.githubusercontent.com/assets/4371545/8330540/80ddf7c6-1ab4-11e5-810e-090f17dda2db.png)

Code is

```
    myTempChart.datasets[0].removePoint(0);
    myHumidityChart.datasets[0].removePoint(0);
    myTempChart.datasets[0].addPoint(date, temperature);
    myHumidityChart.datasets[0].addPoint(date, humidity);

    myTempChart.update();
   myHumidityChart.update();
```

I'm stumped on what the issue might be.

**Comment by dima117** [comment]
Could you give an example on jsfiddle.net or similar site?

**Comment by dima117** [comment]
Also see [this example](http://dima117.github.io/Chart.Scatter/test.html)

```
setInterval(function () {

            var arg = Date.parse("2015-04-27T04:00:00+03:00") + ii * 24 * 3600000;

            myChart.datasets[0].removePoint(0);
            myChart.datasets[1].removePoint(0);

            myChart.datasets[0].addPoint(arg, getRandomInt(0, 100));
            myChart.datasets[1].addPoint(arg, getRandomInt(0, 100));
            myChart.update(), ii++;

        }, 200);
```

**Comment by dima117** [comment]
Also please check the order of your points :)

**Comment by Teddy-Schmitz** [comment]
Thanks for that example,  you can see the behaviour I'm talking about if you don't remove point 0

http://jsfiddle.net/9ozpmk6q/7/

I redid your example a bit to make it more closely match what I'm doing.

**Comment by dima117** [comment]
The reason is in sort order of your points.

Your example uses the following data:

```
{ 
  "results": [ 
    { "humidity": "57.80", "temp": "25.00", "timestamp": 1435230516 },  
    { "humidity": "57.80", "temp": "25.00", "timestamp": 1435230457 }, 
    { "humidity": "58.00", "temp": "25.10", "timestamp": 1435230397 }  
  ]
}
```

and this is the chart
![example chart](https://habrastorage.org/files/514/df2/4b7/514df24b75aa43d2a0b0d32dbde518a5.png)

**Comment by Teddy-Schmitz** [comment]
Your completely right, for some reason I had it in my head that it was sorting it by date.  Thanks for clearing it up.
