### ISSUE TITLE
Custom y-axis labels

### ISSUE THREAD

**Issue by jptheripper** [dima117/Chart.AltLineChart#15]
Is there a possibility to have custom y-axis labels (like from an array)? I have a 6 line -  line graph with date as the x axis, but my y axis is non-numerical, A,B,C,D,E,F (for example)

Thank you

![image](https://cloud.githubusercontent.com/assets/10562464/8526632/e2b03052-23d5-11e5-8f77-897f5750ba92.png)

**Comment by dima117** [comment]
Hi

You can use the 'scaleLabel' option. Set your custom function as a value. Also look at the y-axis range parameters named 'scaleOverride', 'scaleStartValue', 'scaleSteps' and 'scaleStepWidth'.

Please see the example: http://jsfiddle.net/pjvkn1nx/
