### ISSUE TITLE
useUTC for datetime scales seems not to work with Safari

### ISSUE THREAD

**Issue by uenz** [dima117/Chart.AltLineChart#22]
Hi,

useUTC=false for datetime scales seems not to work with Safari (Os X and IPhone)
Here a sample diagram:
https://gist.github.com/anonymous/16efe20dd5f69587af08
With Safari browser a time offset is shown.

**Comment by dima117** [comment]
Hi
I'm sorry for the late reply.
The Safari browser has a bug in Date.parse. Please specify the timezone for your date values. For example: `new Date('2015-07-15T07:07:00.000Z')`

**Comment by uenz** [comment]
Tanks for reply. Didn't know that there is a bug in Safari browsers. 
Your suggestion works for me.
Thx
