### ISSUE TITLE
Points color not updated on refresh

### ISSUE THREAD

**Issue by netcelli-tux** [dima117/Chart.AltLineChart#28]
The color of points in the plot is not changed if update() is called. Here is an example to reproduce the issue: https://jsfiddle.net/rpdwmodc/1/. The script changes the color from orange to black after 3 seconds.
Changing strokeColor property works but not for pointColor.

**Comment by dima117** [comment]
Hi,

This is because there is a special logic of drawing point (changing the color of point on mouse hover) and during chart initialization the colors are memorized separately for each point. The simplest solution - to draw a new chart of a different color with the same data.

**Comment by netcelli-tux** [comment]
Thanks for the suggestion!
