### ISSUE TITLE
Format date in x axis

### ISSUE THREAD

**Issue by oxstormrider** [dima117/Chart.AltLineChart#3]
Hello @dima117.
The 'default' formart for one dateset I am working looks to be 'mmm d', but I would like to change the format to 'mm/yy'.
There is a way to change the format of a date in the x axis?
Thanks.

**Comment by dima117** [comment]
Use the _scaleDateFormat_ option.

**Comment by dima117** [comment]
Hi, @oxstormrider 
Was my answer useful to you?

**Comment by oxstormrider** [comment]
It didn't work here. The scaleDateFormat only change the points labels, not the X axis labels.
But I solved my problem by changing the date format directly in your code.
Thanks for the help.  :+1:

**Comment by dima117** [comment]
Oops, really it was error and it is fixed. Now scaleDateFormat and scaleTimeFormat options works correctly.
See the http://dima117.github.io/Chart.Scatter/test.html
Thank you for your help!

**Comment by dima117** [comment]
Please update your Chart.Scatter.js
