### ISSUE TITLE
this.hasData line 1062 reflects the initial data, breaks initial empty scenario

### ISSUE THREAD

**Issue by Laro88** [dima117/Chart.AltLineChart#37]
I might be missing something vital, however it seems like the this.hasData reflects the initial condition of the data.
So when the chart is initialized with empty arrays then nothing is plotted. addPoint does however not alter the state of hasData - so nothing will ever be rendered.

Am I right so far?

**Comment by dima117** [comment]
Yes you are right.
This code was written before it was possible to add points to the datasets, and I forgot to fix this check.

Error corrected! Thanks for the feedback!
