### ISSUE TITLE
xScaleOverride doesnt work

### ISSUE THREAD

**Issue by ranstyr** [dima117/Chart.AltLineChart#39]
Hi DIma,

when setting the below configuration i expect to see only 5 steps (we can see it is working for y axis):
 xScaleOverride: true,
// *\* Required if scaleOverride is true **
// Number - The number of steps in a hard coded x scale
 xScaleSteps:5,
 //Number - The value jump in the hard coded x scale
 xScaleStepWidth: 50,
 // Number - The x scale starting value
xScaleStartValue: 0

please see example at - https://jsfiddle.net/ranstyr/75m29yhx/

BTW, do you support showXLabels (https://github.com/nnnick/Chart.js/pull/521)?

Thanks,
Ran.

**Comment by dima117** [comment]
Hi,

please update your file Chart.Scatter.js from github.com ( ! )
See the example https://jsfiddle.net/75m29yhx/1/

**Comment by dima117** [comment]
I do not planning to support 'showXLabels' option because this feature has already been implemented as the 'xScaleOverride' option. Also, the wording of the 'showXLabels' option issue is not entirely correct and makes sense for the line chart only.

**Comment by ranstyr** [comment]
Thank you for your great and quick support!
BTW, i am not sure why npm update/install didn't update to the github version (both are 1.1.3)

**Comment by dima117** [comment]
I'm sorry, I have added some changes, but didn't changed the version and didn't publish them to npm/bower yet. I will do it in the near future. 
Please use file from master now.
