### ISSUE TITLE
Time is always in UTC

### ISSUE THREAD

**Issue by jchesterisidoro** [dima117/Chart.AltLineChart#4]
Even if I set the option to false or modified the source code and changed the default configuration to false. Graph still shows UTC format.

**Comment by dima117** [comment]
Could you give an example on http://jsfiddle.net or similar site?

**Comment by jchesterisidoro** [comment]
I'm using it for WebViews in mobile using Appcelerator Titanium for android and iOS. Do you think it's because of that? What I did was download the zip file, and copied ONLY the Chart.Scatter.js. I already have the Chart.js core.

**Comment by dima117** [comment]
I think it's probably a bug. I will try to reproduce and fix it today. If it is possible, make me an example on http://jsfiddle.net or send me your data and chart options.

**Comment by dima117** [comment]
I'm checked how to works useUtc parameter and changed some incorrect behaviour. 

If useUtc parameter is true then date values is interpreted as UTC dates. Else they is interpreted as local dates. It affects to point and scale labels and to scale limits.

Please update your Chart.Scatter.js from GitHub and check, how it works.

**Comment by jchesterisidoro** [comment]
Thanks! The fix is working. I have another issue though. I have this data, 
```
data = [{
	x : 1429977600,
	y : 65.07
}, {
	x : 1430064000,
	y : 62.21
}, {
	x : 1430150400,
	y : 61.07
}]
```
![screenshot_2015-04-28-09-01-18](https://cloud.githubusercontent.com/assets/5276353/7361169/b5e89db4-ed86-11e4-990e-e1985aa6ded7.png)

The data above is the only the green part. It's supposed to show a daily data. But instead of seeing the date as x-axis, you only see the time and you won't have any idea what date it is.

**Comment by jchesterisidoro** [comment]
Thanks! The fix is working. I have another issue though. I have this data, (timestamp is GMT+8, they're 12am)

```
data = [{
    x : 1429977600000,
    y : 65.07
}, {
    x : 1430064000000,
    y : 62.21
}, {
    x : 1430150400000,
    y : 61.07
}]
```

![screenshot_2015-04-28-09-01-18](https://cloud.githubusercontent.com/assets/5276353/7361169/b5e89db4-ed86-11e4-990e-e1985aa6ded7.png)

The data above is the only the green part. It's supposed to show a daily data. But instead of seeing the date as x-axis, you only see the time and you won't have any idea what date it is.

I know that I can use the normal line chart here, but what if there is a day that have no data, so I would still need to use scatter chart here. Thanks for helping.

**Comment by dima117** [comment]
I'm sorry for the delay of my reply . I will try to reproduce your case and will write you.

**Comment by dima117** [comment]
It was my error again. It's fixed. 
http://jsfiddle.net/avdubdw2/1/

Thank you for your help!

**Comment by jchesterisidoro** [comment]
Sorry for the very late reply. I just tried it, and it's working! Thanks for your help! :)
