### ISSUE TITLE
Showing legend

### ISSUE THREAD

**Issue by rkoptev** [dima117/Chart.AltLineChart#47]
Hi, I'mtrying to add a legend to my chart. I did not find the description on project website, so I use the standard way to create legend in Chart.JS plot: I was added div to my page and set html to chart.generateLegend(). It works but instead of normal colored legend i get simple unmarked list with data labels as text. Nothing more.How do I get the correct legend?

**Comment by dima117** [comment]
Can you give an example on jsfiddle.net please

**Comment by rkoptev** [comment]
https://jsfiddle.net/qax8vbr9/

**Comment by dima117** [comment]
In your example the legend does not contain the colors because you are using an incorrect field "lineColor" in the legend template. Please use the "strokeColor" field instead the "lineColor". See the example https://jsfiddle.net/qax8vbr9/1/
