### ISSUE TITLE
Setting up Chart.Scatter with proper files.

### ISSUE THREAD

**Issue by katsuragi545** [dima117/Chart.AltLineChart#48]
I'm a little confused on how to go about properly hooking everything up in order to get Chart.Scatter to work.  Do I need to create a bundle file?  I downloaded the master source zip file - do I only need to include the Chart.Scatter.js file? How does everything from that zip file get referenced?  Sorry if these are trivial - I'm new to web development. 

I've already added Chart.Scatter via npm to my project, but when I try to execute the `.Scatter` function, I get an error saying:

`TypeError: (intermediate value).Scatter is not a function`

I also get the error:

`Uncaught TypeError: Cannot read property 'extend' of undefined'` 

in Chart.Scatter.js when I start up my webpage. Any ideas?

**Comment by dima117** [comment]
Hello,
you need to include two files into your page: 
- `Chart.min.js` - this is the Chart.js core
- `Chart.Scatter.min.js` - this is a scatter chart plugin

For example, if you install the scatter chart via npm then needed files are located:
- `node_modules/chart.js-scatter/node_modules/chart.js/Chart.min.js`
- `node_modules/chart.js-scatter/Chart.Scatter.min.js`
