### ISSUE TITLE
Strange jitter

### ISSUE THREAD

**Issue by ppcat** [dima117/Chart.AltLineChart#49]
Hi,

I found some strange jitter when my chart got a lot of data within it. Just like below image, it should like clear square-type chart, but when data value changed, it got jitters.
![2016-07-18 3 29 06](https://cloud.githubusercontent.com/assets/776439/16908292/e3a71f9c-4cfc-11e6-8c99-a076a8030a10.png)

[JSBin](http://jsbin.com/xavagubayu/edit?js,output)
Did i do something wrong with config? Thank you very much!

Mike

**Comment by dima117** [comment]
Hi,

I'm sorry for the late reply.

Please set the `bezierCurve` to `false`. See the example on [jsbin](http://jsbin.com/nozapowaxi/2/edit?js,output).

**Comment by ppcat** [comment]
It works like a charm. Sorry I thought that `bezierCurve` is default to `false`. It's my mistake. Thank you!
