### ISSUE TITLE
Allow animation of chart using .update()

### ISSUE THREAD

**Issue by martinpetts** [dima117/Chart.AltLineChart#7]
Calling myChart.update(); results in the following error:
TypeError: undefined is not a function (evaluating 'myChart.update()')
Does the scatter chart not work with the Chart.js API?

**Comment by dima117** [comment]
Hi
The data structures of the scatter chart are different from data structure of other chart types. And so some parts of the Chart.js API are not applicable to scatter chart.

Please give me an example on http://jsfiddle.net or similar site, so I can see the whole sequence of method calls and their parameters. And I will try to make your code a workable.

**Comment by martinpetts** [comment]
This is a simplified version of what I want to achieve...
http://jsbin.com/zadanirovi/2/edit?html,js,console,output

**Comment by dima117** [comment]
Hi
I added the "update" method into Scatter chart type. But you must use the special methods of datasets for change it data.

```
// Add a new point { x: 5, y: 7 }
myChart.datasets[0].addPoint(5, 7);

// Set point data { x: 11, y: 4 } at index 3
myChart.datasets[0].setPointData(3, 11, 4);

// Remove the point at index 0
myChart.datasets[0].removePoint(0);
...
myChart.update();
```

We need these special methods for automatically calculating some point parameters.

**Comment by dima117** [comment]
See an example on http://dima117.github.io/Chart.Scatter/test.html

**Comment by dima117** [comment]
Does it solve your problem?

**Comment by dima117** [comment]
If there are no objections, I will close this issue. Feel free to contact me, if you have any questions or suggestions.

**Comment by martinpetts** [comment]
Hi - sorry for the delayed response. This does go a long way towards solving my problem, thanks. The only things I need to look into are why the animation starts from zero for each change in the points, i.e. it doesn't move between the old values and the new, rather it animates from zero each time. 

Also, I need to be able to fix the scale, so it's not moving about with the changes in values, but this is a separate issue I think.

**Comment by majuansari** [comment]
Hi,

Can I hide or delete a certain data set ? Say if have 4 Datasets for countries China,US,Rus & Mexico, what if I want to hide China from the chart ?
