### ISSUE TITLE
LegendTemplate misplaced  html tag close span before dataset

### ISSUE THREAD

**Issue by fd694309** [dima117/Chart.AltLineChart#9]
In Chart.Scatter.js line 201 the html tag `</span>` Is before `<%=datasets[i].label`. it should be after the dataset (but before the `</li>`)
Also in Chart.Scatter.min.js

**Comment by dima117** [comment]
That `<span>` tag is a label marker (it has a "scatter-legend-marker" class) and so it located before the label. Please, see the example: http://jsfiddle.net/romL16s5/

If you need to other legend template, please change the default value.

```
new Chart(ctx).Scatter(data, {
    legendTemplate: "<<< your legend template >>>"
});
```

**Comment by fd694309** [comment]
The HTML tag < / span >

**Comment by dima117** [comment]
Yes, I meant all tags of that element.
